// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package db

import (
	"time"

	"github.com/google/uuid"
)

type File struct {
	FileID           uuid.UUID
	OriginalFilename string
	EncryptedDek     []byte
	SizeBytes        int64
	CreatedAt        time.Time
}
