// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package db

import (
	"context"

	"github.com/google/uuid"
)

type Querier interface {
	// queries.sql — input to sqlc. Each `-- name:` block becomes a method on *Queries.
	// The trailing tag controls the return shape:
	//   :one  -> returns a single row (error if zero)
	//   :many -> returns a slice
	//   :exec -> returns only error (no rows)
	CreateFile(ctx context.Context, arg CreateFileParams) (File, error)
	// DeleteFile is the compensating action when the DB insert succeeds but a later
	// step fails, or for the orphan sweep. Keeps the "row exists => blob exists" invariant.
	DeleteFile(ctx context.Context, fileID uuid.UUID) error
	GetFile(ctx context.Context, fileID uuid.UUID) (File, error)
}

var _ Querier = (*Queries)(nil)
