// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: queries.sql

package db

import (
	"context"

	"github.com/google/uuid"
)

const createFile = `-- name: CreateFile :one

INSERT INTO files (file_id, original_filename, encrypted_dek, size_bytes)
VALUES ($1, $2, $3, $4)
RETURNING file_id, original_filename, encrypted_dek, size_bytes, created_at
`

type CreateFileParams struct {
	FileID           uuid.UUID
	OriginalFilename string
	EncryptedDek     []byte
	SizeBytes        int64
}

// queries.sql — input to sqlc. Each `-- name:` block becomes a method on *Queries.
// The trailing tag controls the return shape:
//
//	:one  -> returns a single row (error if zero)
//	:many -> returns a slice
//	:exec -> returns only error (no rows)
func (q *Queries) CreateFile(ctx context.Context, arg CreateFileParams) (File, error) {
	row := q.db.QueryRow(ctx, createFile,
		arg.FileID,
		arg.OriginalFilename,
		arg.EncryptedDek,
		arg.SizeBytes,
	)
	var i File
	err := row.Scan(
		&i.FileID,
		&i.OriginalFilename,
		&i.EncryptedDek,
		&i.SizeBytes,
		&i.CreatedAt,
	)
	return i, err
}

const deleteFile = `-- name: DeleteFile :exec
DELETE FROM files
WHERE file_id = $1
`

// DeleteFile is the compensating action when the DB insert succeeds but a later
// step fails, or for the orphan sweep. Keeps the "row exists => blob exists" invariant.
func (q *Queries) DeleteFile(ctx context.Context, fileID uuid.UUID) error {
	_, err := q.db.Exec(ctx, deleteFile, fileID)
	return err
}

const getFile = `-- name: GetFile :one
SELECT file_id, original_filename, encrypted_dek, size_bytes, created_at
FROM files
WHERE file_id = $1
`

func (q *Queries) GetFile(ctx context.Context, fileID uuid.UUID) (File, error) {
	row := q.db.QueryRow(ctx, getFile, fileID)
	var i File
	err := row.Scan(
		&i.FileID,
		&i.OriginalFilename,
		&i.EncryptedDek,
		&i.SizeBytes,
		&i.CreatedAt,
	)
	return i, err
}
